apiVersion: v1
kind: Service
metadata:
  name: {{ include "moscowtime.fullname" . }}
  labels:
    {{- include "moscowtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.out_port }}
      targetPort: {{ .Values.service.container_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "moscowtime.selectorLabels" . | nindent 4 }}
