apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "moscowtime.fullname" . }}
  labels:
    {{- include "moscowtime.labels" . | nindent 4 }}
spec:
  podManagementPolicy: "Parallel"
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "moscowtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "moscowtime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "moscowtime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.container_port }}
              protocol: {{ .Values.service.protocol }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
#            env:
#              - name: HELM_USER
#                valueFrom:
#                  secretKeyRef:
#                    name: moscowtime-secret2
#                    key: user
#              - name: HELM_PASS
#                valueFrom:
#                  secretKeyRef:
#                    name: moscowtime-secret2
#                    key: pass
          volumeMounts:
            - name: {{ .Values.volumes.configuration.name }}
              mountPath: {{ .Values.volumes.configuration.mountPath }}
              subPath: {{ .Values.volumes.configuration.subPath }}
      volumes:
        - name: test
          emptyDir: {}
        - name: {{ .Values.volumes.configuration.name }}
          configMap:
            name: {{ include "moscowtime.fullname" . }}-config
      initContainers:
          - name: test
            image: busybox:1.28
            command:
              - wget
              - "-O"
              - "/app/test/index.html"
              - http://info.cern.ch
            volumeMounts:
              - name: test
                mountPath: "/app/test/"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volumes.storage.name }}
      {{ - with .Values.volumes.storage.spec }}
      spec:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
